### ISSUE TITLE
black blank screen for bar code scanner page

### ISSUE THREAD

**Issue by vickynathaiya** [xulihang/cordova-plugin-dynamsoft-barcode-reader#1]
When I  click on "Scan Barcodes" button, its just showing black blank screen with bottom fab button, no issue in the console, may be issue with camera preview.

**Comment by xulihang** [comment]
Which sample are you using?

**Comment by vickynathaiya** [comment]
https://github.com/xulihang/Ionic-Angular-Cordova-Barcode-Scanner

**Comment by xulihang** [comment]
Are you running on iOS or Android? It works fine on iOS 15 and Android 10.

**Comment by vickynathaiya** [comment]
I am running on real android 10.0 device

**Comment by xulihang** [comment]
I've updated the sample to install the plugin from npm directly. You can try it again.

**Comment by vickynathaiya** [comment]
still same issue, code not running after  let result = await DBR.init(this.
license);  on barcode-scanner.component.ts

**Comment by xulihang** [comment]
Please make sure that you've followed the steps in the readme.

**Comment by vickynathaiya** [comment]
I did exact what you write in your read me file,
1. cloned repo
2. npm i
3. ionic cordova platform add android
4. ionic cordova prepare android

opened android studio, connect my device and build app on my device

**Comment by xulihang** [comment]
You can check out the logs to see what happened.

**Comment by xulihang** [comment]
I've updated the sample to add the license. You can try it again.

Please note that the plugin puts the camera view behind the webview. The webview is set to transparent so that we can see the camera. You may have to update the styles to see the camera in your case.

**Comment by xulihang** [comment]
Please post further issues here: https://github.com/xulihang/Ionic-Angular-Cordova-Barcode-Scanner

**Comment by xulihang** [comment]
I've uploaded an apk file which works for me: https://github.com/xulihang/Ionic-Angular-Cordova-Barcode-Scanner/releases/download/builds/app-debug.apk

**Comment by vickynathaiya** [comment]
there is no error logs or warning logs in android studio

BTW below are more details about versions I am using for this project, hope
it could help you find issue:

Ionic:

   Ionic CLI                     : 6.16.3
   Ionic Framework               : @ionic/angular 6.1.8
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.3.7
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0,
cordova-plugin-ionic-webview 5.0.0, (and 4 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.4.0

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v14.17.1
   npm               : 8.10.0
   OS                : Windows 10

**Comment by xulihang** [comment]
Please post your issues here: https://github.com/tony-xlh/Ionic-Angular-Cordova-Barcode-Scanner/issues

I think it is related to the dark theme. The demo was updated so that the dark theme will not be used.
